### ISSUE TITLE
Yarn Install Error: "workspaces config expects an Array"

### ISSUE THREAD

**Issue by stakez** [replayio/replay-cli#228]
I am running into this issue when upgrade my packages to the latest version

```error app/packages/app/node_modules/@replayio/cypress: Command failed.
Exit code: 1

Command: npm run if:dist -- node ./bin/replayio-cypress first-run

Arguments: 

Directory: /Users/stephenakaeze/Desktop/guide/packages/app/node_modules/@replayio/cypress

Output:
TypeError: workspaces config expects an Array
    at getError (/usr/local/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/lib/index.js:66:24)
    at getPatterns (/usr/local/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/lib/index.js:36:11)
    at mapWorkspaces (/usr/local/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/lib/index.js:82:20)
    at Config.loadLocalPrefix (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:676:34)
    at async Config.loadProjectConfig (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:607:5)```

What is happening here?

**Comment by ryanjduffy** [comment]
@stakez Sorry for the delayed response. This seems like a confusion between workspaces and our package but I haven't seen it before. Couple options:

* Record a replay of the command that's throwing with `replay-node`: https://docs.replay.io/reference-guide/recording/replay-node-(experimental). Something like: `replay-node --exec yarn upgrade @replayio/cypress` and then upload the replay with our CLI.
* Share a bit more about your configuration and I'll see if I can reproduce it.

**Comment by stakez** [comment]
@ryanjduffy for the response. This was dumped during nom install but I am not using your package directly. It is coming from [react-hook-form](https://www.npmjs.com/package/react-hook-form?activeTab=dependencies). I forced a yarn update on packages which must have triggered this. Please close this issue for now. If it happens in the future, I will follow up with the authors of react-hook-form before returning.

**Comment by stakez** [comment]
@ryanjduffy for the response. This was dumped during nom install but I am not using your package directly. It is coming from [react-hook-form](https://www.npmjs.com/package/react-hook-form?activeTab=dependencies). I forced a yarn update on packages which must have triggered this. I will close this issue for now. If it happens in the future, I will follow up with the authors of react-hook-form before returning.
