### ISSUE TITLE
playwright - peer dependencies 

### ISSUE THREAD

**Issue by jycouet** [replayio/replay-cli#92]
I get a warning with `pnpm` when I use: `@replayio/playwright`

```
└─┬ @replayio/playwright 0.3.0
  └── ✕ unmet peer @playwright/test@1.19.x: found 1.27.1
```

I guess that in https://github.com/replayio/replay-cli/blob/main/packages/playwright/package.json#L43, you could set: `"@playwright/test": "^1.19.x"`?

**Comment by Andarist** [comment]
In the upcoming version of our `@replayio/playwright` we are setting the peer dep correctly here:
https://github.com/replayio/replay-cli/blob/d7500696513b610e2ab4248f07ac617a0538c49b/packages/playwright/package.json#L55-L57
